AWSTemplateFormatVersion: 2010-09-09
Description: secure internet gateway appliance security subnet
Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Required Select according to your NW
        Parameters:
          - NetworkName
          - KeyName
      -
        Label:
          default: Select according to your NW
        Parameters:
          - SyslogSecurityLeftPrivateInterface
          - SyslogSecurityRightPrivateInterface
          - linuxInstanceType

Parameters: 
  NetworkName:
    Description: Network name
    Type: String
    Default: tgw

  KeyName:
    Description: Key name
    Type: String
    Default: tokyoregion2

  SyslogSecurityLeftPrivateInterface:
    Description: the I/F address of the private sbunet
    Type: String
    Default: 172.16.10.10
    AllowedPattern: ^([0-9]+\.){3}[0-9]+$
    MaxLength: 15
    MinLength: 7

  SyslogSecurityRightPrivateInterface:
    Description: the I/F address of the private sbunet
    Type: String
    Default: 172.16.20.10
    AllowedPattern: ^([0-9]+\.){3}[0-9]+$
    MaxLength: 15
    MinLength: 7

  linuxInstanceType:
    Description: linux instance type to use for your instances.
    Type: String
    AllowedValues:
      - t2.micro # min linux default
      - t2.small # min fg default
      - t2.medium
      - t3.micro
      - t3.small
      - t3.medium
    Default: t2.micro

Mappings: 
  AmiAmazonLinuxMap:
    ap-northeast-1: # tokyo
      ami: ami-0bba69335379e17f8
    ap-northeast-3: # osaka
      ami: ami-0e0cbf0f03ba99ee7
    ap-northeast-2: # seoul
      ami: ami-0eddbd81024d3fbdd

Resources: 
# ------- Title Syslog SV Left Instance -------
  SyslogLeftInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      ImageId: !FindInMap [AmiAmazonLinuxMap, !Ref AWS::Region, ami]
      InstanceType: !Ref linuxInstanceType
      Monitoring: false
      SourceDestCheck: false
      NetworkInterfaces:
        - AssociatePublicIpAddress: True
          DeviceIndex: 0
          Description: public interface of Fortiate
          PrivateIpAddress: !Ref SyslogSecurityLeftPrivateInterface
          GroupSet:
            - !ImportValue
              Fn::Sub: ${NetworkName}-SyslogLeftSG
          SubnetId: !ImportValue
              Fn::Sub: ${NetworkName}-GLBeGatewayLeftSubnet
      Tags:
        - Key: Name
          Value: !Sub ${NetworkName}-Syslog-Left-Instance

# --------- Title Syslog Security Right Subnet ----------
  SyslogRightInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      ImageId: !FindInMap [AmiAmazonLinuxMap, !Ref AWS::Region, ami]
      InstanceType: !Ref linuxInstanceType
      Monitoring: false
      SourceDestCheck: false
      NetworkInterfaces:
        - AssociatePublicIpAddress: True
          DeviceIndex: 0
          Description: public interface of Fortiate
          PrivateIpAddress: !Ref SyslogSecurityRightPrivateInterface
          GroupSet:
            - !ImportValue
              Fn::Sub: ${NetworkName}-SyslogRightSG
          SubnetId: !ImportValue
              Fn::Sub: ${NetworkName}-GLBeGatewayRightSubnet
      Tags:
        - Key: Name
          Value: !Sub ${NetworkName}-Syslog-Right-Instance

#Outputs:
